Repository wecode-bootcamp-korea/23-1st-Seocaso-frontend, pull requests merged in 2021-08, with the labels that each got.

#5 [23기 김다슬] Add : Footer 레이아웃 완료
  .eslintrc
  .prettierrc
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.scss
  src/pages/Main/Footer.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: Status: 리뷰 요청

#2 [23기 김다슬] Modify : 코드리뷰 반영하여 리팩토링 완료
  .eslintrc
  .gitignore
  .prettierrc
  package-lock.json
  package.json
  public/data/Mockdata.json
  public/data/ReviewRankingData.json
  public/data/StarRankingData.json
  public/images/main_thumbnail01.jpg
  public/images/main_thumbnail02.jpg
  public/images/main_thumbnail03.jpg
  public/images/main_thumbnail04.jpg
  public/images/main_thumbnail05.jpg
  public/images/main_thumbnail06.jpg
  public/images/main_thumbnail07.jpg
  public/images/main_thumbnail08.jpg
  public/images/main_thumbnail09.jpg
  public/images/main_thumbnail10.jpg
  public/images/main_thumbnail11.jpg
  public/images/main_thumbnail12.jpg
  public/images/main_thumbnail13.jpg
  public/images/seocaso_logo.png
  public/images/thumbnail.jpg
  public/index.html
  src/Routes.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/Login/Login.js
  src/components/Nav/Nav.js
  src/components/Nav/Signup/Signup.js
  src/components/Nav/Signup/Signup.scss
  src/index.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/RankList/RankList.js
  src/pages/Main/RankList/RankList.scss
  src/pages/Main/Ranking/Ranking.js
  src/pages/Main/Ranking/Ranking.scss
  src/pages/Product/Product.js
  src/pages/Product/Product.scss
  src/styles/common.scss
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#6 [23기 김다슬] Add : 검색 결과 페이지 레이아웃 완료
  public/data/SearchResultData.json
  public/index.html
  src/Routes.js
  src/index.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Search/Search.js
  src/pages/Search/Search.scss
  src/pages/Search/SearchList.js
  src/pages/Search/SearchResult.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#8 [23기 김다슬] Add : 상세페이지 Review 부분 레이아웃 완료
  .prettierrc
  public/index.html
  src/Routes.js
  src/index.js
  src/pages/Product/Review.js
  src/pages/Product/Review.scss
  src/pages/Product/ReviewModal.js
  src/pages/Product/ReviewModal.scss
Labels: Status: Conflict 해결 요청

#7 [23기 김다슬] Add : Footer 상단 별점 총 카운트 완료
  .vscode/settings.json
  src/Routes.js
  src/components/Footer/Footer.js
  src/config.js
  src/pages/Main/Footer.js
Labels: Status: Accepted

#3 [23기 문주영] Modify: 로그인 회원가입 Nav바 연결완료
  .gitignore
  package-lock.json
  package.json
  public/data/Likedata.json
  public/images/amationmark.png
  public/images/backimg2.jpg
  public/images/checkmark.png
  public/images/x-mark.png
  public/index.html
  src/Routes.js
  src/components/Nav/Login/Login.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/image/backimg2.jpg
  src/image/rose.jpg
  src/index.js
  src/pages/Login/LoginModal.js
  src/pages/Login/LoginModal.scss
  src/pages/Main/Main.js
  src/pages/Modal/Button.js
  src/pages/Modal/Form.js
  src/pages/Modal/Form.scss
  src/pages/Modal/Input.js
  src/pages/Modal/Layout.js
  src/pages/Modal/Modal.js
  src/pages/Modal/Modal.scss
  src/pages/Product/Product.js
  src/pages/Signup/SignupModal.js
  src/pages/Signup/SignupModal.scss
  src/styles/common.scss
Labels: Status: 리뷰 요청

#1 [23기 소진수] Modify : Conflict 해결 완료
  .vscode/settings.json
  public/data/Mockdata.json
  public/images/backimg1.jpg
  src/Routes.js
  src/assets/images/GreyStar.svg
  src/assets/images/HalfStar.svg
  src/assets/images/TheHalfStar.svg
  src/assets/images/YellowStar.svg
  src/assets/images/backimg1.jpg
  src/assets/images/backimg2.jpg
  src/assets/images/backimg3.jpg
  src/assets/images/backimg4.jpg
  src/assets/images/backimg5.jpg
  src/assets/images/star.svg
  src/assets/images/starbrown.svg
  src/assets/images/talk.jpg
  src/assets/images/thumb.jpg
  src/index.js
  src/pages/Login/LoginModal.js
  src/pages/Main/Main.js
  src/pages/Modal/Button.js
  src/pages/Modal/Form.js
  src/pages/Modal/Input.js
  src/pages/Modal/Layout.js
  src/pages/Modal/Modal.js
  src/pages/Product/Body/Body.js
  src/pages/Product/Body/Body.scss
  src/pages/Product/Body/Comment.js
  src/pages/Product/Body/Comment.scss
  src/pages/Product/Body/Comment/CommentCard.js
  src/pages/Product/Body/Graph.js
  src/pages/Product/Body/Graph.scss
  src/pages/Product/Body/Info.js
  src/pages/Product/Body/Info.scss
  src/pages/Product/Body/Menu.js
  src/pages/Product/Body/Menu.scss
  src/pages/Product/Body/Menu/CoffeeMenu.js
  src/pages/Product/Body/Review.js
  src/pages/Product/Body/Review.scss
  src/pages/Product/Body/Review/ReviewModal.js
  src/pages/Product/Body/Review/ReviewModal.scss
  src/pages/Product/Body/SideInfo.js
  src/pages/Product/Body/SideInfo.scss
  src/pages/Product/Body/SideInfo/Image/Image.js
  src/pages/Product/Body/SideInfo/Image/ImageModal.js
  src/pages/Product/Body/SideInfo/Image/ImageModal.scss
  src/pages/Product/Product.js
  src/pages/Product/Top/LikeBtn.js
  src/pages/Product/Top/LikeBtn.scss
  src/pages/Product/Top/Stars.js
  src/pages/Product/Top/Stars.scss
  src/pages/Product/Top/TheStar.js
  src/pages/Product/Top/TheStar.scss
  src/pages/Product/Top/Top.js
  src/pages/Product/Top/Top.scss
  src/pages/Search/Search.js
  src/pages/Search/SearchList.js
  src/pages/Search/SearchResult.js
  src/pages/Signup/SignupModal.js
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#11 [23기 김다슬] Modify : search 데이터 통신 완료
  src/Routes.js
  src/config.js
  src/pages/Search/Search.js
  src/pages/Search/Search.scss
  src/pages/Search/SearchList.js
Labels: Status: 리뷰 요청

#10 [23기 소진수] modify : 마이페이지 기능구현 완료
  public/data/Mockdata 2.json
  src/assets/images/cafe1.jpg
  src/assets/images/cafe2.jpg
  src/assets/images/cafe3.jpg
  src/assets/images/cafe4.jpg
  src/assets/images/cafe5.jpg
  src/assets/images/cafe6.jpg
  src/assets/images/images.md
  src/assets/images/main_thumbnail01.jpg
  src/assets/images/main_thumbnail02.jpg
  src/assets/images/main_thumbnail03.jpg
  src/assets/images/main_thumbnail04.jpg
  src/assets/images/main_thumbnail05.jpg
  src/assets/images/main_thumbnail06.jpg
  src/assets/images/main_thumbnail07.jpg
  src/assets/images/main_thumbnail08.jpg
  src/assets/images/main_thumbnail09.jpg
  src/assets/images/main_thumbnail10.jpg
  src/assets/images/main_thumbnail11.jpg
  src/assets/images/main_thumbnail12.jpg
  src/assets/images/main_thumbnail13.jpg
  src/assets/images/profilephoto.png
  src/assets/images/seocaso_logo.png
  src/assets/images/thumbnail.jpg
  src/pages/MyPage/Evaluation.js
  src/pages/MyPage/Filter.js
  src/pages/MyPage/Filter.scss
  src/pages/MyPage/Like.js
  src/pages/MyPage/Mypage.js
  src/pages/MyPage/Mypage.scss
Labels: Status: 리뷰 요청
